# Generated by Django 4.2 on 2024-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='card_users', to='accounts.card'),
        ),
    ]
