# Generated by Django 4.2 on 2024-04-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_hashtag_article_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
    ]
